import { Station } from './types';

export const stations: Station[] = [
  { id: 'churchgate', name: 'Churchgate', lines: ['western'] },
  { id: 'marine-lines', name: 'Marine Lines', lines: ['western'] },
  { id: 'charni-road', name: 'Charni Road', lines: ['western'] },
  { id: 'grant-road', name: 'Grant Road', lines: ['western'] },
  { id: 'mumbai-central', name: 'Mumbai Central', lines: ['western'] },
  { id: 'mahalaxmi', name: 'Mahalaxmi', lines: ['western'] },
  { id: 'lower-parel', name: 'Lower Parel', lines: ['western'] },
  { id: 'elphinstone', name: 'Elphinstone Road', lines: ['western'] },
  { id: 'dadar-w', name: 'Dadar', lines: ['western', 'central'] },
  { id: 'matunga-road', name: 'Matunga Road', lines: ['western'] },
  { id: 'mahim', name: 'Mahim', lines: ['western'] },
  { id: 'bandra', name: 'Bandra', lines: ['western', 'harbour'] },
  { id: 'khar-road', name: 'Khar Road', lines: ['western'] },
  { id: 'santacruz', name: 'Santacruz', lines: ['western'] },
  { id: 'vile-parle', name: 'Vile Parle', lines: ['western'] },
  { id: 'andheri', name: 'Andheri', lines: ['western', 'harbour', 'metro-1'] },
  { id: 'jogeshwari', name: 'Jogeshwari', lines: ['western'] },
  { id: 'goregaon', name: 'Goregaon', lines: ['western'] },
  { id: 'malad', name: 'Malad', lines: ['western'] },
  { id: 'kandivali', name: 'Kandivali', lines: ['western'] },
  { id: 'borivali', name: 'Borivali', lines: ['western'] },
  { id: 'dahisar', name: 'Dahisar', lines: ['western'] },
  { id: 'mira-road', name: 'Mira Road', lines: ['western'] },
  { id: 'bhayandar', name: 'Bhayandar', lines: ['western'] },
  { id: 'naigaon', name: 'Naigaon', lines: ['western'] },
  { id: 'vasai-road', name: 'Vasai Road', lines: ['western'] },
  { id: 'virar', name: 'Virar', lines: ['western'] },
  { id: 'csmt', name: 'CSMT', lines: ['central', 'harbour'] },
  { id: 'masjid', name: 'Masjid', lines: ['central'] },
  { id: 'sandhurst-road', name: 'Sandhurst Road', lines: ['central', 'harbour'] },
  { id: 'byculla', name: 'Byculla', lines: ['central'] },
  { id: 'chinchpokli', name: 'Chinchpokli', lines: ['central'] },
  { id: 'currey-road', name: 'Currey Road', lines: ['central'] },
  { id: 'parel', name: 'Parel', lines: ['central'] },
  { id: 'dadar-c', name: 'Dadar', lines: ['central'] },
  { id: 'matunga', name: 'Matunga', lines: ['central'] },
  { id: 'sion', name: 'Sion', lines: ['central'] },
  { id: 'kurla', name: 'Kurla', lines: ['central', 'harbour'] },
  { id: 'vidyavihar', name: 'Vidyavihar', lines: ['central'] },
  { id: 'ghatkopar', name: 'Ghatkopar', lines: ['central', 'metro-1'] },
  { id: 'vikhroli', name: 'Vikhroli', lines: ['central'] },
  { id: 'bhandup', name: 'Bhandup', lines: ['central'] },
  { id: 'nahur', name: 'Nahur', lines: ['central'] },
  { id: 'mulund', name: 'Mulund', lines: ['central'] },
  { id: 'thane', name: 'Thane', lines: ['central'] },
  { id: 'kalyan', name: 'Kalyan', lines: ['central'] },
  { id: 'cotton-green', name: 'Cotton Green', lines: ['harbour'] },
  { id: 'reay-road', name: 'Reay Road', lines: ['harbour'] },
  { id: 'dockyard-road', name: 'Dockyard Road', lines: ['harbour'] },
  { id: 'sewri', name: 'Sewri', lines: ['harbour'] },
  { id: 'wadala-road', name: 'Wadala Road', lines: ['harbour'] },
  { id: 'gtb-nagar', name: 'GTB Nagar', lines: ['harbour'] },
  { id: 'chunabhatti', name: 'Chunabhatti', lines: ['harbour'] },
  { id: 'tilak-nagar', name: 'Tilak Nagar', lines: ['harbour'] },
  { id: 'chembur', name: 'Chembur', lines: ['harbour'] },
  { id: 'govandi', name: 'Govandi', lines: ['harbour'] },
  { id: 'mankhurd', name: 'Mankhurd', lines: ['harbour'] },
  { id: 'vashi', name: 'Vashi', lines: ['harbour'] },
  { id: 'panvel', name: 'Panvel', lines: ['harbour'] },
  { id: 'bkc', name: 'BKC', lines: ['metro-1'] },
  { id: 'versova', name: 'Versova', lines: ['metro-1'] },
  { id: 'dn-nagar', name: 'D.N. Nagar', lines: ['metro-1'] },
  { id: 'azad-nagar', name: 'Azad Nagar', lines: ['metro-1'] },
  { id: 'chakala', name: 'Chakala', lines: ['metro-1'] },
  { id: 'marol-naka', name: 'Marol Naka', lines: ['metro-1'] },
  { id: 'saki-naka', name: 'Saki Naka', lines: ['metro-1'] },
  { id: 'asalpha', name: 'Asalpha', lines: ['metro-1'] },
  { id: 'jagruti-nagar', name: 'Jagruti Nagar', lines: ['metro-1'] },
];

export function searchStations(query: string): Station[] {
  const q = query.toLowerCase().trim();
  if (!q) return stations;
  return stations.filter((s) => s.name.toLowerCase().includes(q));
}
